test([
  'class Foo {}',
  'Foo *foo() { return null; }',
], [
]);

test([
  'class A {}',
  'class B : A {}',
  '',
  'void foo(A *a, B *b) {',
  '  a = b;',
  '  b = a;',
  '  b = (B *)a;',
  '  *a = *a;',
  '  *a = copy *a;',
  '  *a = move *a;',
  '  *a = *b;',
  '  *b = *a;',
  '  *b = *b;',
  '  *b = move *b;',
  '  *b = copy *b;',
  '}',
], [
  'error on line 6 of <stdin>: cannot convert from pointer of type A* to pointer of type B* without a cast',
  '',
  '  b = a;',
  '      ^',
  '',
  'error on line 8 of <stdin>: need "move" or "copy" to convert from value of type A to value of type A',
  '',
  '  *a = *a;',
  '       ~~',
  '',
  'error on line 11 of <stdin>: cannot convert from value of type B to value of type A',
  '',
  '  *a = *b;',
  '       ~~',
  '',
  'error on line 12 of <stdin>: cannot convert from value of type A to value of type B',
  '',
  '  *b = *a;',
  '       ~~',
  '',
  'error on line 13 of <stdin>: need "move" or "copy" to convert from value of type B to value of type B',
  '',
  '  *b = *b;',
  '       ~~',
]);

test([
  'class A {}',
  'class B : A {}',
  '',
  'void foo(A &a, B &b) {',
  '  a = a;',
  '  a = move a;',
  '  a = copy a;',
  '  a = b;',
  '  b = a;',
  '  b = b;',
  '  b = move b;',
  '  b = copy b;',
  '}',
], [
  'error on line 5 of <stdin>: need "move" or "copy" to convert from reference of type A& to reference of type A&',
  '',
  '  a = a;',
  '      ^',
  '',
  'error on line 8 of <stdin>: cannot convert from reference of type B& to reference of type A&',
  '',
  '  a = b;',
  '      ^',
  '',
  'error on line 9 of <stdin>: cannot convert from reference of type A& to reference of type B&',
  '',
  '  b = a;',
  '      ^',
  '',
  'error on line 10 of <stdin>: need "move" or "copy" to convert from reference of type B& to reference of type B&',
  '',
  '  b = b;',
  '      ^',
]);

test([
  'class Foo {}',
  'Foo val;',
  'Foo &ref;',
  'Foo *ptr;',
], [
  'error on line 3 of <stdin>: variable of type Foo& must be initialized',
  '',
  'Foo &ref;',
  '     ~~~',
]);

test([
  'class Foo {}',
  '',
  'void foo() {',
  '  Foo val;',
  '  Foo &ref = val;',
  '  Foo *ptr = &val;',
  '',
  '  val = val;',
  '  val = move val;',
  '  val = copy val;',
  '  val = ref;',
  '  val = move ref;',
  '  val = copy ref;',
  '  val = ptr;',
  '  val = *ptr;',
  '  val = move *ptr;',
  '  val = copy *ptr;',
  '',
  '  ref = val;',
  '  ref = move val;',
  '  ref = copy val;',
  '  ref = ref;',
  '  ref = move ref;',
  '  ref = copy ref;',
  '  ref = ptr;',
  '  ref = *ptr;',
  '  ref = move *ptr;',
  '  ref = copy *ptr;',
  '',
  '  ptr = val;',
  '  ptr = &val;',
  '  ptr = ref;',
  '  ptr = &ref;',
  '  ptr = ptr;',
  '}',
], [
  'error on line 8 of <stdin>: need "move" or "copy" to convert from value of type Foo to value of type Foo',
  '',
  '  val = val;',
  '        ~~~',
  '',
  'error on line 11 of <stdin>: need "move" or "copy" to convert from reference of type Foo& to value of type Foo',
  '',
  '  val = ref;',
  '        ~~~',
  '',
  'error on line 14 of <stdin>: cannot convert from pointer of type Foo* to value of type Foo',
  '',
  '  val = ptr;',
  '        ~~~',
  '',
  'error on line 15 of <stdin>: need "move" or "copy" to convert from value of type Foo to value of type Foo',
  '',
  '  val = *ptr;',
  '        ~~~~',
  '',
  'error on line 19 of <stdin>: need "move" or "copy" to convert from value of type Foo to reference of type Foo&',
  '',
  '  ref = val;',
  '        ~~~',
  '',
  'error on line 22 of <stdin>: need "move" or "copy" to convert from reference of type Foo& to reference of type Foo&',
  '',
  '  ref = ref;',
  '        ~~~',
  '',
  'error on line 25 of <stdin>: cannot convert from pointer of type Foo* to reference of type Foo&',
  '',
  '  ref = ptr;',
  '        ~~~',
  '',
  'error on line 26 of <stdin>: need "move" or "copy" to convert from value of type Foo to reference of type Foo&',
  '',
  '  ref = *ptr;',
  '        ~~~~',
  '',
  'error on line 30 of <stdin>: cannot convert from value of type Foo to pointer of type Foo*',
  '',
  '  ptr = val;',
  '        ~~~',
  '',
  'error on line 32 of <stdin>: cannot convert from reference of type Foo& to pointer of type Foo*',
  '',
  '  ptr = ref;',
  '        ~~~',
]);

test([
  'class Foo {}',
  '',
  'void _val(Foo val) {}',
  'void _ref(Foo &ref) {}',
  'void _ptr(Foo *ptr) {}',
  '',
  'void foo() {',
  '  Foo val;',
  '  Foo &ref = val;',
  '  Foo *ptr = &val;',
  '',
  '  _val(val);',
  '  _val(move val);',
  '  _val(copy val);',
  '  _val(ref);',
  '  _val(move ref);',
  '  _val(copy ref);',
  '  _val(ptr);',
  '  _val(*ptr);',
  '  _val(move *ptr);',
  '  _val(copy *ptr);',
  '',
  '  _ref(val);',
  '  _ref(move val);',
  '  _ref(copy val);',
  '  _ref(ref);',
  '  _ref(move ref);',
  '  _ref(copy ref);',
  '  _ref(ptr);',
  '  _ref(*ptr);',
  '  _ref(move *ptr);',
  '  _ref(copy *ptr);',
  '',
  '  _ptr(val);',
  '  _ptr(&val);',
  '  _ptr(ref);',
  '  _ptr(&ref);',
  '  _ptr(ptr);',
  '}',
], [
  'error on line 12 of <stdin>: need "move" or "copy" to convert from value of type Foo to value of type Foo',
  '',
  '  _val(val);',
  '       ~~~',
  '',
  'error on line 15 of <stdin>: need "move" or "copy" to convert from reference of type Foo& to value of type Foo',
  '',
  '  _val(ref);',
  '       ~~~',
  '',
  'error on line 18 of <stdin>: cannot convert from pointer of type Foo* to value of type Foo',
  '',
  '  _val(ptr);',
  '       ~~~',
  '',
  'error on line 19 of <stdin>: need "move" or "copy" to convert from value of type Foo to value of type Foo',
  '',
  '  _val(*ptr);',
  '       ~~~~',
  '',
  'error on line 29 of <stdin>: cannot convert from pointer of type Foo* to reference of type Foo&',
  '',
  '  _ref(ptr);',
  '       ~~~',
  '',
  'error on line 34 of <stdin>: cannot convert from value of type Foo to pointer of type Foo*',
  '',
  '  _ptr(val);',
  '       ~~~',
  '',
  'error on line 36 of <stdin>: cannot convert from reference of type Foo& to pointer of type Foo*',
  '',
  '  _ptr(ref);',
  '       ~~~',
]);

test([
  'class Foo {}',
  '',
  'Foo _val() {',
  '  Foo val;',
  '  Foo &ref = val;',
  '  Foo *ptr = &val;',
  '',
  '  return val;',
  '  return move val;',
  '  return copy val;',
  '  return ref;',
  '  return move ref;',
  '  return copy ref;',
  '  return ptr;',
  '  return *ptr;',
  '  return move *ptr;',
  '  return copy *ptr;',
  '}',
  '',
  'Foo &_ref() {',
  '  Foo val;',
  '  Foo &ref = val;',
  '  Foo *ptr = &val;',
  '',
  '  return val;',
  '  return move val;',
  '  return copy val;',
  '  return ref;',
  '  return move ref;',
  '  return copy ref;',
  '  return ptr;',
  '  return *ptr;',
  '  return move *ptr;',
  '  return copy *ptr;',
  '}',
  '',
  'Foo &_ptr() {',
  '  Foo val;',
  '  Foo &ref = val;',
  '  Foo *ptr = &val;',
  '',
  '  return val;',
  '  return &val;',
  '  return ref;',
  '  return &ref;',
  '  return ptr;',
  '}',
], [
  'error on line 8 of <stdin>: need "move" or "copy" to convert from value of type Foo to value of type Foo',
  '',
  '  return val;',
  '         ~~~',
  '',
  'error on line 11 of <stdin>: need "move" or "copy" to convert from reference of type Foo& to value of type Foo',
  '',
  '  return ref;',
  '         ~~~',
  '',
  'error on line 14 of <stdin>: cannot convert from pointer of type Foo* to value of type Foo',
  '',
  '  return ptr;',
  '         ~~~',
  '',
  'error on line 15 of <stdin>: need "move" or "copy" to convert from value of type Foo to value of type Foo',
  '',
  '  return *ptr;',
  '         ~~~~',
  '',
  'error on line 31 of <stdin>: cannot convert from pointer of type Foo* to reference of type Foo&',
  '',
  '  return ptr;',
  '         ~~~',
  '',
  'error on line 43 of <stdin>: cannot convert from pointer of type Foo* to reference of type Foo&',
  '',
  '  return &val;',
  '         ~~~~',
  '',
  'error on line 45 of <stdin>: cannot convert from pointer of type Foo* to reference of type Foo&',
  '',
  '  return &ref;',
  '         ~~~~',
  '',
  'error on line 46 of <stdin>: cannot convert from pointer of type Foo* to reference of type Foo&',
  '',
  '  return ptr;',
  '         ~~~',
]);

test([
  'class Foo {}',
  '',
  'Foo _val() {}',
  'Foo &_ref() {}',
  'Foo *_ptr() {}',
  '',
  'void foo() {',
  '  Foo val;',
  '  Foo &ref = val;',
  '  Foo *ptr = &val;',
  '',
  '  val = _val();',
  '  val = move _val();',
  '  val = copy _val();',
  '  val = _ref();',
  '  val = move _ref();',
  '  val = copy _ref();',
  '  val = _ptr();',
  '  val = *_ptr();',
  '  val = move *_ptr();',
  '  val = copy *_ptr();',
  '',
  '  ref = _val();',
  '  ref = move _val();',
  '  ref = copy _val();',
  '  ref = _ref();',
  '  ref = move _ref();',
  '  ref = copy _ref();',
  '  ref = _ptr();',
  '  ref = *_ptr();',
  '  ref = move *_ptr();',
  '  ref = copy *_ptr();',
  '',
  '  ptr = _val();',
  '  ptr = &_val();',
  '  ptr = _ref();',
  '  ptr = &_ref();',
  '  ptr = _ptr();',
  '}',
], [
  'error on line 13 of <stdin>: move is already implied for temporary values',
  '',
  '  val = move _val();',
  '        ~~~~~~~~~~~',
  '',
  'error on line 14 of <stdin>: move is already implied for temporary values',
  '',
  '  val = copy _val();',
  '        ~~~~~~~~~~~',
  '',
  'error on line 15 of <stdin>: need "move" or "copy" to convert from reference of type Foo& to value of type Foo',
  '',
  '  val = _ref();',
  '        ~~~~~~',
  '',
  'error on line 18 of <stdin>: cannot convert from pointer of type Foo* to value of type Foo',
  '',
  '  val = _ptr();',
  '        ~~~~~~',
  '',
  'error on line 19 of <stdin>: need "move" or "copy" to convert from value of type Foo to value of type Foo',
  '',
  '  val = *_ptr();',
  '        ~~~~~~~',
  '',
  'error on line 24 of <stdin>: move is already implied for temporary values',
  '',
  '  ref = move _val();',
  '        ~~~~~~~~~~~',
  '',
  'error on line 25 of <stdin>: move is already implied for temporary values',
  '',
  '  ref = copy _val();',
  '        ~~~~~~~~~~~',
  '',
  'error on line 26 of <stdin>: need "move" or "copy" to convert from reference of type Foo& to reference of type Foo&',
  '',
  '  ref = _ref();',
  '        ~~~~~~',
  '',
  'error on line 29 of <stdin>: cannot convert from pointer of type Foo* to reference of type Foo&',
  '',
  '  ref = _ptr();',
  '        ~~~~~~',
  '',
  'error on line 30 of <stdin>: need "move" or "copy" to convert from value of type Foo to reference of type Foo&',
  '',
  '  ref = *_ptr();',
  '        ~~~~~~~',
  '',
  'error on line 34 of <stdin>: cannot convert from value of type Foo to pointer of type Foo*',
  '',
  '  ptr = _val();',
  '        ~~~~~~',
  '',
  'error on line 36 of <stdin>: cannot convert from reference of type Foo& to pointer of type Foo*',
  '',
  '  ptr = _ref();',
  '        ~~~~~~',
]);
