test([
  'class A {}',
  'class B : A {}',
  '',
  'void foo(A *a, B *b) {',
  '  a = b;',
  '  b = a;',
  '  b = (B *)a;',
  '  *a = *a;',
  '  *a = copy *a;',
  '  *a = move *a;',
  '  *a = *b;',
  '  *b = *a;',
  '  *b = *b;',
  '  *b = move *b;',
  '  *b = copy *b;',
  '}',
], [
  'error on line 6 of <stdin>: cannot convert from pointer of type A* to pointer of type B* without a cast',
  '',
  '  b = a;',
  '      ^',
  '',
  'error on line 8 of <stdin>: need "move" or "copy" to convert from value of type A to value of type A',
  '',
  '  *a = *a;',
  '       ~~',
  '',
  'error on line 11 of <stdin>: cannot convert from value of type B to value of type A',
  '',
  '  *a = *b;',
  '       ~~',
  '',
  'error on line 12 of <stdin>: cannot convert from value of type A to value of type B',
  '',
  '  *b = *a;',
  '       ~~',
  '',
  'error on line 13 of <stdin>: need "move" or "copy" to convert from value of type B to value of type B',
  '',
  '  *b = *b;',
  '       ~~',
]);
